/**
 * MCFunction Export
 * Generates /fill and /setblock commands from StructureData
 */

import { StructureData } from '../types/index'
import { getAllNonAirBlocks } from '../core/StructureData'

export interface MCFunctionOptions {
  relativeTo?: { x: number; y: number; z: number }
  useExecute?: boolean
  groupByY?: boolean
  addComments?: boolean
}

/**
 * Generate MCFunction file content from StructureData
 */
export function exportMCFunction(
  structure: StructureData,
  options: MCFunctionOptions = {}
): string {
  const { relativeTo = { x: 0, y: 0, z: 0 }, addComments = true } = options
  const lines: string[] = []

  if (addComments) {
    lines.push(`# Generated by MIneLAb`)
    lines.push(`# Structure: ${structure.name}`)
    lines.push(`# Dimensions: ${structure.dimensions.x}x${structure.dimensions.y}x${structure.dimensions.z}`)
    lines.push(`# Generated: ${new Date().toISOString()}`)
    lines.push('')
  }

  // Group blocks by layer
  const blocksByY = new Map<number, Array<{ pos: { x: number; y: number; z: number }; blockId: string }>>()

  const allBlocks = getAllNonAirBlocks(structure)
  for (const { pos, blockId } of allBlocks) {
    const y = pos.y
    if (!blocksByY.has(y)) blocksByY.set(y, [])
    blocksByY.get(y)!.push({ pos, blockId })
  }

  // Sort layers
  const sortedYLevels = Array.from(blocksByY.keys()).sort((a, b) => a - b)

  for (const y of sortedYLevels) {
    const blocks = blocksByY.get(y)!
    if (addComments && blocks.length > 0) {
      lines.push(`# Layer Y=${y}`)
    }

    for (const { pos, blockId } of blocks) {
      const wx = pos.x + relativeTo.x
      const wy = pos.y + relativeTo.y
      const wz = pos.z + relativeTo.z

      // Format block ID - strip minecraft: prefix for shorthand or keep full ID
      const blockIdFormatted = blockId.startsWith('minecraft:') ? blockId : `minecraft:${blockId}`

      lines.push(`setblock ${wx} ${wy} ${wz} ${blockIdFormatted}`)
    }

    if (addComments) lines.push('')
  }

  return lines.join('\n')
}

/**
 * Generate optimized //fill commands for WorldEdit
 * Groups adjacent same-type blocks into fill regions
 */
export function exportWorldEditFill(
  structure: StructureData,
  options: { relativeTo?: { x: number; y: number; z: number } } = {}
): string {
  const { relativeTo = { x: 0, y: 0, z: 0 } } = options
  const lines: string[] = []

  lines.push(`# WorldEdit Fill Commands`)
  lines.push(`# Generated by MIneLAb - Structure: ${structure.name}`)
  lines.push(`# Paste these at your target location`)
  lines.push('')

  // Simple approach: one setblock per block
  // TODO: Optimize with fill regions using greedy algorithm
  const allBlocks = getAllNonAirBlocks(structure)

  for (const { pos, blockId } of allBlocks) {
    const wx = pos.x + relativeTo.x
    const wy = pos.y + relativeTo.y
    const wz = pos.z + relativeTo.z
    const blockIdFormatted = blockId.startsWith('minecraft:') ? blockId : `minecraft:${blockId}`
    lines.push(`//setblock ${wx} ${wy} ${wz} ${blockIdFormatted}`)
  }

  return lines.join('\n')
}

/**
 * Export structure as Datapack zip (generates the file content as a string description)
 * Full implementation would use fflate to create a zip
 */
export function exportDatapackInfo(structure: StructureData): {
  packMcmeta: string
  functionContent: string
  fileName: string
} {
  const safeName = structure.name.toLowerCase().replace(/[^a-z0-9_]/g, '_')

  const packMcmeta = JSON.stringify({
    pack: {
      pack_format: 48,
      description: `${structure.name} - Generated by MIneLAb`
    }
  }, null, 2)

  const functionContent = exportMCFunction(structure, { addComments: true })

  return {
    packMcmeta,
    functionContent,
    fileName: `${safeName}.zip`
  }
}
